site_name: Bike Itaú / tembice.

nav:
  - Home: index.md
  - Apresentações : apresentacoes.md
  - Planejamneto: ''
  - Pré-rastreabilidade:
    - Rich Picture: Pre-rastreabilidade/richpicture.md
  - Elicitação:
    - Brainstorming: elicitacao/brainstorming.md
    - Introspecção: elicitacao/introspeccao.md
    - Personas: elicitacao/personas.md
    - Storytelling: elicitacao/storytelling.md
  - Priorização:
    - MoSCoW: priorizacao/moscow.md
  - Modelagem:
    - Ágil:
      - História de Usuários: modelagem/agil/historias.md
    - Backlog : modelagem/backlog.md
    - Caso de Uso: modelagem/casodeuso.md
    - Cenários: modelagem/cenarios.md
    - Especificação Suplementar: modelagem/especSuplementar.md
    - Léxicos: modelagem/lexicos.md
docs_dir: docs/

theme: 
  name: material
  custon_dir: overrides
  palette:
    primary: orange
  language: pt 
  icon:
    logo: material/bicycle
    favicon: material/bicycle
  features:
    - navigation.tracking
    