site_name: Bike Itaú / tembice.

nav:
  - Home: index.md
  - Apresentações : apresentacoes.md
  - Planejamneto: ''
  - Pré-rastreabilidade:
    - Caso de Uso: Pre-rastreabilidade/casodeuso.md
    - Storytelling: Pre-rastreabilidade/storytelling.md
docs_dir: docs/

theme: 
  name: material
  custon_dir: overrides
  palette:
    primary: orange
  language: pt 
  icon:
    logo: material/bicycle
    favicon: material/bicycle
  features:
    - navigation.tracking
    